### ISSUE TITLE
Installing via scoop reports wrong hashsum

### ISSUE THREAD

**Issue by mk0x9** [fsprojects/Forge#47]
```
PS C:\Users\mk9> scoop install forge
installing forge (0.6.0)
downloading https://github.com/fsprojects/Forge/releases/download/0.6.0/forge.zip...done
checking hash...hash check failed for https://github.com/fsprojects/Forge/releases/download/0.6.0/forge.zip. expected: 66316278C884B8C00D167DC78255528B, actual: b71adc9850e3d3ee13a9c2664e1eb36b!
```

**Comment by henriqueprj** [comment]
+1

**Comment by Simon-Campbell** [comment]
I have raised a PR to match the hash of the file in the releases tag of this section https://github.com/lukesampson/scoop/pull/696

**Comment by Simon-Campbell** [comment]
The hash mismatch PR has been merged to scoop repo.

While that does correct the hash mismatch (after running `scoop update`) it looks like installing 0.6.0 leads to other issues.

```
Unhandled Exception: System.Exception: Argu: parameter '-h' is reserved for the 'usage' parameter.
   at Argu.ArgInfo.commandLineArgs@248.Invoke(String message)
   at Argu.ArgInfo.preComputeArgInfo(UnionCaseInfo uci)
   at Microsoft.FSharp.Collections.IEnumerator.map@111.DoMoveNext(b& )
   at Microsoft.FSharp.Collections.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at Microsoft.FSharp.Collections.SeqModule.ToArray[T](IEnumerable`1 source)
   at Microsoft.FSharp.Collections.SeqModule.SortBy@1512.Invoke(Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.mkDelayedSeq@881.Invoke(Unit unitVar0)
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Argu.ArgumentParser`1..ctor(FSharpOption`1 usageText)
   at ForgeLib.main(String[] argv)
```

**Comment by cloudRoutine** [comment]
@Simon-Campbell this has already been fixed in src, it'll be resolved in the next release

**Comment by Krzysztof-Cieslak** [comment]
Waiting for https://github.com/lukesampson/scoop/pull/715 to be merged
